#!/bin/sh -eu


clean() {
    rm -rf aclocal.m4 \
       autom4te.cache \
       autoscan.log \
       compile \
       config.guess \
       config.log \
       config.sub \
       configure \
       configure~ \
       configure.scan \
       depcomp \
       install-sh \
       missing \
       ar-lib \
       ltmain.sh \
       m4/libtool.m4 \
       m4/ltoptions.m4 \
       m4/ltsugar.m4 \
       m4/ltversion.m4 \
       test-driver \
       m4/lt~obsolete.m4

    find src -name Makefile.in -delete
    rm -rf Makefile.in
}

usage() {
    cat <<EOF
Usage: $(basename $0) [options]

Options:
  -c, --clean      Remove all files generated by autoreconf
  -h, --help       Print help page
EOF
}


for arg in "$@"; do
    case "$arg" in
	-c|--clean)
	    clean
	    exit 0
	    ;;
	-h|--help)
	    usage
	    exit 0
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done


autoreconf -iv -Wall
