---
name: Autotools on multiple platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, macos-14, macos-15]
        compiler: [gcc, clang]
        include:
          - os: ubuntu-24.04
            compiler: gcc
          - os: ubuntu-24.04
            compiler: clang
          - os: macos-14
            compiler: clang
          - os: macos-15
            compiler: clang
        exclude:
          - os: macos-14
            compiler: gcc
          - os: macos-15
            compiler: gcc

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y check

    - name: Setup packages
      if: runner.os == 'macOS'
      run: |
        brew install autoconf automake check libtool

    - name: Configure
      run: |
        ./bootstrap.sh
        mkdir ${{ steps.strings.outputs.build-output-dir }}
        cd ${{ steps.strings.outputs.build-output-dir }}
        ../configure CC=${{ matrix.compiler }}

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: make

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: make check
